export enum PAYMENT_METHODS {
    GOOGLE_PAY = "GOOGLE_PAY",
    STRIPE = "STRIPE",
    POD = "POD",
    COD = "COD",
}


export enum ORDER_STATUS {
    CONFIRMED = 'CONFIRMED',
    PROCESSING = 'PROCESSING',
    OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
    PENDING = 'PENDING',
    COMPLETED = 'COMPLETED',
    CANCELLED = 'CANCELLED',
};